# Generated by Django 3.0.7 on 2022-10-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='sexo',
            field=models.CharField(choices=[('M', 'masculino'), ('F', 'femenino'), ('OTRO', 'otro')], max_length=6),
        ),
    ]
