# Generated by Django 3.0.7 on 2022-10-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20221020_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='pais',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Colombia', 'Colombia'), ('Peru', 'Peru')], default=1, max_length=15),
        ),
    ]
