# Generated by Django 3.2.19 on 2023-05-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_personas_precio_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='precio_semana',
            field=models.FloatField(default=0),
        ),
    ]
